{% set name = "skore-hub-project" %}
{% set version = "0.0.23" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skore_hub_project-{{ version }}.tar.gz
  sha256: df58c976c84203bcb8fa7f751c25ee7be7143cf1f6469e5f0fee36b42ce9245f

build:
  entry_points:
    - skore.plugins.login.hub = skore_hub_project.authentication.login:login
    - skore.plugins.project.hub = skore_hub_project.project.project:Project
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - httpx
    - joblib
    - matplotlib-base
    - numpy
    - orjson
    - pydantic
    - rich[jupyter] >=14.2
    - scikit-learn
    - scipy

test:
  imports:
    - skore_hub_project
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/probabl-ai/skore
  summary: the scikit-learn sidekick
  description: |
    Skore helps data scientists focus on what matters: building
    impactful models with hindsight and clarity.
  doc_url: https://skore.probabl.ai
  dev_url: https://github.com/probabl-ai/skore
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - auguste-probabl
    - glemaitre
    - rouk1
    - thomass-dev
    - tuscland
